version: '3.8'

services:
  db:
    image: postgres:16
    container_name: medcore_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medcore_secret}
      POSTGRES_DB: ${POSTGRES_DB:-medcore}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: medcore_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@medcore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: medcore_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api.Dockerfile
    container_name: medcore_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB:-medcore};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-medcore_secret}
      - RedisConnection=redis:6379
    ports:
      - '5000:8080'
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  redisdata:
